name: Swift Build & Release

on:
  workflow_dispatch: 
  push:              
    branches:
      - simon/static-releases

jobs:
  run:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4

      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.1"

      - name: Build Swift Package
        run: |
          mkdir -p .build/release
          swift build -c release -Xswiftc -DNO_AUTOMATIC_UPDATE

      - name: Prepare Release Assets
        run: |
          mkdir -p /tmp/release-action/assets
          
          cp .build/release/automa /tmp/release-action/assets/
          
          zip -r /tmp/release-action/assets/source.zip . -x ".build/*"
          
          echo '{"title":"test-release ({action-new-version})","bump":"{commit-message}","description":"This is an automated release process! This CLI Distribution is used by many of our build processes.","description-adders":["commits","new-contributors","diff-from-previous-release"]}' > /tmp/release-action/release-config.json

      - name: Create Release
        uses: GetAutomaApp/opensource-actions/release@simon/implement-release-action
        with:
          github-token: ${{ secrets.PAT_GITHUB_RELEASE_BUILD_TOKEN }}
          config-path: /tmp/release-action/release-config.json
          assets-path: /tmp/release-action/assets
